theme = "default"
client_id = "65b708073fc0480ea92a077233ca87bd"
client_port = 8080
playback_format = """
{track} • {album}
{artists}

{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "⏸"
liked_icon = "♥"
border_type = "Hidden"
progress_bar_type = "Line"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 4
cover_img_scale = 1.0
playback_window_width = 6
enable_media_control = true
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "Spotify Player TUI"

[copy_command]
command = "xclip"
args = [
    "-sel",
    "c",
]

[notify_format]
summary = "{track} • {album}"
body = "{artists}"

[device]
name = "Spotify Player TUI"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
